
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - conn
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 5000
    networks:
      - conn
networks:
  conn:
    driver: bridge